//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 10:29:41 AM CST 
//


package plfx.jd.pojo.qo.ylclient;

import java.io.Serializable;


@SuppressWarnings("serial")
public class JDOrderQO implements Serializable{
	/**
	 * 订单编号
	 */
    protected long orderId;
    public long getOrderId() {
        return orderId;
    }

    public void setOrderId(long value) {
        this.orderId = value;
    }

}
