package plfx.yeexing.inter;



import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IBEServicePortType", targetNamespace = "http://service.webservice.yeexing.com")
public interface IBEServicePortType {

	/**
	 * 
	 * @param startDate
	 * @param cabin
	 * @param stopNumber
	 * @param orgCity
	 * @param airCompany
	 * @param endDate
	 * @param airGet
	 * @param dsgCity
	 * @param sign
	 * @param flight
	 * @param planeType
	 * @param tickType
	 * @param userName
	 * @param cabinType
	 * @param ticketPrice
	 * @param airSource
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirpolicyNoEncrypt")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirpolicyNoEncrypt", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpolicyNoEncrypt")
	@ResponseWrapper(localName = "QueryAirpolicyNoEncryptResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpolicyNoEncryptResponse")
	public String queryAirpolicyNoEncrypt(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dsgCity", targetNamespace = "") String dsgCity,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "endDate", targetNamespace = "") String endDate,
			@WebParam(name = "airCompany", targetNamespace = "") String airCompany,
			@WebParam(name = "flight", targetNamespace = "") String flight,
			@WebParam(name = "cabin", targetNamespace = "") String cabin,
			@WebParam(name = "cabinType", targetNamespace = "") String cabinType,
			@WebParam(name = "planeType", targetNamespace = "") String planeType,
			@WebParam(name = "ticketPrice", targetNamespace = "") String ticketPrice,
			@WebParam(name = "stopNumber", targetNamespace = "") String stopNumber,
			@WebParam(name = "airGet", targetNamespace = "") String airGet,
			@WebParam(name = "airSource", targetNamespace = "") String airSource,
			@WebParam(name = "tickType", targetNamespace = "") String tickType,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startTime
	 * @param userName
	 * @param type
	 * @param endTime
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryReturnTicketsList")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryReturnTicketsList", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryReturnTicketsList")
	@ResponseWrapper(localName = "QueryReturnTicketsListResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryReturnTicketsListResponse")
	public String queryReturnTicketsList(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "startTime", targetNamespace = "") String startTime,
			@WebParam(name = "endTime", targetNamespace = "") String endTime,
			@WebParam(name = "type", targetNamespace = "") String type,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outOrderid
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Order_QueryStatusContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Order_QueryStatusContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryStatusContract")
	@ResponseWrapper(localName = "Order_QueryStatusContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryStatusContractResponse")
	public String orderQueryStatusContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param payPlatform
	 * @param payNotifyUrl
	 * @param totalPrice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PayOut")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PayOut", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PayOut")
	@ResponseWrapper(localName = "PayOutResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PayOutResponse")
	public String payOut(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "totalPrice", targetNamespace = "") String totalPrice,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "pay_notify_url", targetNamespace = "") String payNotifyUrl,
			@WebParam(name = "out_notify_url", targetNamespace = "") String outNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param orderStatus
	 * @param timeSlot
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryOrderIdByStatus")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryOrderIdByStatus", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryOrderIdByStatus")
	@ResponseWrapper(localName = "QueryOrderIdByStatusResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryOrderIdByStatusResponse")
	public String queryOrderIdByStatus(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "timeSlot", targetNamespace = "") String timeSlot,
			@WebParam(name = "orderStatus", targetNamespace = "") String orderStatus,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airId
	 * @param passengername
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryRefundByOutOrderId")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryRefundByOutOrderId", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryRefundByOutOrderId")
	@ResponseWrapper(localName = "QueryRefundByOutOrderIdResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryRefundByOutOrderIdResponse")
	public String queryRefundByOutOrderId(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengername", targetNamespace = "") String passengername,
			@WebParam(name = "airId", targetNamespace = "") String airId,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airId
	 * @param passengerName
	 * @param userName
	 * @param orderid
	 * @param refundSegment
	 * @param refundMemo
	 * @param refundType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "RefundTicketByOutOrderId")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "RefundTicketByOutOrderId", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundTicketByOutOrderId")
	@ResponseWrapper(localName = "RefundTicketByOutOrderIdResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundTicketByOutOrderIdResponse")
	public String refundTicketByOutOrderId(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengerName", targetNamespace = "") String passengerName,
			@WebParam(name = "airId", targetNamespace = "") String airId,
			@WebParam(name = "refundType", targetNamespace = "") String refundType,
			@WebParam(name = "refundMemo", targetNamespace = "") String refundMemo,
			@WebParam(name = "refundSegment", targetNamespace = "") String refundSegment,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param payPlatform
	 * @param payNotifyUrl
	 * @param totalPrice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Pay")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Pay", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.Pay")
	@ResponseWrapper(localName = "PayResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PayResponse")
	public String pay(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "totalPrice", targetNamespace = "") String totalPrice,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "pay_notify_url", targetNamespace = "") String payNotifyUrl,
			@WebParam(name = "out_notify_url", targetNamespace = "") String outNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param filterCondition
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AcquireAllAirp")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AcquireAllAirp", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AcquireAllAirp")
	@ResponseWrapper(localName = "AcquireAllAirpResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AcquireAllAirpResponse")
	public String acquireAllAirp(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "filterCondition", targetNamespace = "") String filterCondition,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airId
	 * @param passengerName
	 * @param refundNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param refundSegment
	 * @param refundMemo
	 * @param refundType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "RefundTicket")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "RefundTicket", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.RefundTicket")
	@ResponseWrapper(localName = "RefundTicketResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.RefundTicketResponse")
	public String refundTicket(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengerName", targetNamespace = "") String passengerName,
			@WebParam(name = "airId", targetNamespace = "") String airId,
			@WebParam(name = "refundType", targetNamespace = "") String refundType,
			@WebParam(name = "refundMemo", targetNamespace = "") String refundMemo,
			@WebParam(name = "refundSegment", targetNamespace = "") String refundSegment,
			@WebParam(name = "refund_notify_url", targetNamespace = "") String refundNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startTime
	 * @param startDate
	 * @param dstCity
	 * @param userName
	 * @param airCompany
	 * @param orgCity
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryFlight")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryFlight", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.QueryFlight")
	@ResponseWrapper(localName = "QueryFlightResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.QueryFlightResponse")
	public String queryFlight(
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dstCity", targetNamespace = "") String dstCity,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "startTime", targetNamespace = "") String startTime,
			@WebParam(name = "airCompany", targetNamespace = "") String airCompany,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param endCallTime
	 * @param userName
	 * @param startCallTime
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirpSyncTime")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirpSyncTime", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpSyncTime")
	@ResponseWrapper(localName = "QueryAirpSyncTimeResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpSyncTimeResponse")
	public String queryAirpSyncTime(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "startCallTime", targetNamespace = "") String startCallTime,
			@WebParam(name = "endCallTime", targetNamespace = "") String endCallTime,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param cabin
	 * @param pnr
	 * @param startday
	 * @param plcid
	 * @param discount
	 * @param sign
	 * @param tickettype
	 * @param dstcity
	 * @param orgcity
	 * @param officeno
	 * @param userName
	 * @param bestdiscount
	 * @param flightno
	 * @param airline
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ReturnAnalysis")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ReturnAnalysis", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ReturnAnalysis")
	@ResponseWrapper(localName = "ReturnAnalysisResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ReturnAnalysisResponse")
	public String returnAnalysis(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orgcity", targetNamespace = "") String orgcity,
			@WebParam(name = "dstcity", targetNamespace = "") String dstcity,
			@WebParam(name = "airline", targetNamespace = "") String airline,
			@WebParam(name = "cabin", targetNamespace = "") String cabin,
			@WebParam(name = "flightno", targetNamespace = "") String flightno,
			@WebParam(name = "startday", targetNamespace = "") String startday,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "discount", targetNamespace = "") String discount,
			@WebParam(name = "bestdiscount", targetNamespace = "") String bestdiscount,
			@WebParam(name = "officeno", targetNamespace = "") String officeno,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "tickettype", targetNamespace = "") String tickettype,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnr
	 * @param userName
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrBook")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrBook", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBook")
	@ResponseWrapper(localName = "PnrBookResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookResponse")
	public String pnrBook(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startTime
	 * @param userName
	 * @param endTime
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DrawBounceTicketRecord")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "DrawBounceTicketRecord", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.DrawBounceTicketRecord")
	@ResponseWrapper(localName = "DrawBounceTicketRecordResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.DrawBounceTicketRecordResponse")
	public String drawBounceTicketRecord(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "startTime", targetNamespace = "") String startTime,
			@WebParam(name = "endTime", targetNamespace = "") String endTime,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airId
	 * @param passengername
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Refund_Query")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Refund_Query", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundQuery")
	@ResponseWrapper(localName = "Refund_QueryResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundQueryResponse")
	public String refundQuery(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengername", targetNamespace = "") String passengername,
			@WebParam(name = "airId", targetNamespace = "") String airId,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param lastUpdateTime
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AirpSync")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AirpSync", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpSync")
	@ResponseWrapper(localName = "AirpSyncResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpSyncResponse")
	public String airpSync(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "lastUpdateTime", targetNamespace = "") String lastUpdateTime,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airId
	 * @param passengername
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Refund_QueryContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Refund_QueryContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundQueryContract")
	@ResponseWrapper(localName = "Refund_QueryContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundQueryContractResponse")
	public String refundQueryContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengername", targetNamespace = "") String passengername,
			@WebParam(name = "airId", targetNamespace = "") String airId,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param drccomppost
	 * @param drccompname
	 * @param loginname
	 * @param localcity
	 * @param drcname
	 * @param loginpwd
	 * @param userName
	 * @param drccomptel
	 * @param drccompadd
	 * @param drcmobile
	 * @param drcemail
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "RegisterNewUser")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "RegisterNewUser", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RegisterNewUser")
	@ResponseWrapper(localName = "RegisterNewUserResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RegisterNewUserResponse")
	public String registerNewUser(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "loginname", targetNamespace = "") String loginname,
			@WebParam(name = "loginpwd", targetNamespace = "") String loginpwd,
			@WebParam(name = "drcname", targetNamespace = "") String drcname,
			@WebParam(name = "drcmobile", targetNamespace = "") String drcmobile,
			@WebParam(name = "drcemail", targetNamespace = "") String drcemail,
			@WebParam(name = "localcity", targetNamespace = "") String localcity,
			@WebParam(name = "drccompname", targetNamespace = "") String drccompname,
			@WebParam(name = "drccompadd", targetNamespace = "") String drccompadd,
			@WebParam(name = "drccomptel", targetNamespace = "") String drccomptel,
			@WebParam(name = "drccomppost", targetNamespace = "") String drccomppost,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param startTime
	 * @param sign
	 * @param startDate
	 * @param dstCity
	 * @param airComp
	 * @param orgCity
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirpBySegment")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirpBySegment", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpBySegment")
	@ResponseWrapper(localName = "QueryAirpBySegmentResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpBySegmentResponse")
	public String queryAirpBySegment(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign,
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dstCity", targetNamespace = "") String dstCity,
			@WebParam(name = "airComp", targetNamespace = "") String airComp,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ResupplyOrder")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ResupplyOrder", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ResupplyOrder")
	@ResponseWrapper(localName = "ResupplyOrderResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ResupplyOrderResponse")
	public String resupplyOrder(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AirpSyncLastDate")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AirpSyncLastDate", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpSyncLastDate")
	@ResponseWrapper(localName = "AirpSyncLastDateResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpSyncLastDateResponse")
	public String airpSyncLastDate(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnr
	 * @param userName
	 * @param linkman
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrBookDetail")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrBookDetail", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookDetail")
	@ResponseWrapper(localName = "PnrBookDetailResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookDetailResponse")
	public String pnrBookDetail(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "linkman", targetNamespace = "") String linkman,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param ip
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "IPTest")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "IPTest", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.IPTest")
	@ResponseWrapper(localName = "IPTestResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.IPTestResponse")
	public String ipTest(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "ip", targetNamespace = "") String ip,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param outorderid
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryOrderStatus")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryOrderStatus", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryOrderStatus")
	@ResponseWrapper(localName = "QueryOrderStatusResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryOrderStatusResponse")
	public String queryOrderStatus(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "outorderid", targetNamespace = "") String outorderid,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outOrderid
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Order_QueryStatus")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Order_QueryStatus", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryStatus")
	@ResponseWrapper(localName = "Order_QueryStatusResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryStatusResponse")
	public String orderQueryStatus(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airId
	 * @param passengerName
	 * @param refundNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @param refundSegment
	 * @param refundMemo
	 * @param refundType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "RefundTicketContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "RefundTicketContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundTicketContract")
	@ResponseWrapper(localName = "RefundTicketContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefundTicketContractResponse")
	public String refundTicketContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengerName", targetNamespace = "") String passengerName,
			@WebParam(name = "airId", targetNamespace = "") String airId,
			@WebParam(name = "refundType", targetNamespace = "") String refundType,
			@WebParam(name = "refundMemo", targetNamespace = "") String refundMemo,
			@WebParam(name = "refundSegment", targetNamespace = "") String refundSegment,
			@WebParam(name = "refund_notify_url", targetNamespace = "") String refundNotifyUrl,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param appPassword
	 * @param userName
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UserSign")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "UserSign", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.UserSign")
	@ResponseWrapper(localName = "UserSignResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.UserSignResponse")
	public String userSign(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "appPassword", targetNamespace = "") String appPassword,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @param linkman
	 * @param appUserName
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrBookDetailContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrBookDetailContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBookDetailContract")
	@ResponseWrapper(localName = "ParsePnrBookDetailContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBookDetailContractResponse")
	public String parsePnrBookDetailContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "linkman", targetNamespace = "") String linkman,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param cabin
	 * @param ibePrice
	 * @param departureDateTime
	 * @param passengerXml
	 * @param plcid
	 * @param adultOutOrderid
	 * @param disc
	 * @param sign
	 * @param extReward
	 * @param childOutOrderid
	 * @param flightNo
	 * @param userName
	 * @param departureCode
	 * @param arrivalCode
	 * @param officeNum
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CreatePnrBookTickets")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "CreatePnrBookTickets", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.CreatePnrBookTickets")
	@ResponseWrapper(localName = "CreatePnrBookTicketsResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.CreatePnrBookTicketsResponse")
	public String createPnrBookTickets(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "officeNum", targetNamespace = "") String officeNum,
			@WebParam(name = "passengerXml", targetNamespace = "") String passengerXml,
			@WebParam(name = "flightNo", targetNamespace = "") String flightNo,
			@WebParam(name = "cabin", targetNamespace = "") String cabin,
			@WebParam(name = "departureCode", targetNamespace = "") String departureCode,
			@WebParam(name = "arrivalCode", targetNamespace = "") String arrivalCode,
			@WebParam(name = "departureDateTime", targetNamespace = "") String departureDateTime,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "adultOut_orderid", targetNamespace = "") String adultOutOrderid,
			@WebParam(name = "childOut_orderid", targetNamespace = "") String childOutOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnr
	 * @param userName
	 * @param appUserName
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrBookContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrBookContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookContract")
	@ResponseWrapper(localName = "PnrBookContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookContractResponse")
	public String pnrBookContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param id
	 * @param ordaird
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Refuse")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Refuse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.Refuse")
	@ResponseWrapper(localName = "RefuseResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.RefuseResponse")
	public String refuse(
			@WebParam(name = "id", targetNamespace = "") String id,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "ordaird", targetNamespace = "") String ordaird,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param passengerInfo
	 * @param userName
	 * @param outorderid
	 * @param orderid
	 * @param encryptString
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "BookTicket")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "BookTicket", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.BookTicket")
	@ResponseWrapper(localName = "BookTicketResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.BookTicketResponse")
	public String bookTicket(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "encryptString", targetNamespace = "") String encryptString,
			@WebParam(name = "passengerInfo", targetNamespace = "") String passengerInfo,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "outorderid", targetNamespace = "") String outorderid,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param cancelNotifyUrl
	 * @param passengerName
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CancelTicketContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "CancelTicketContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.CancelTicketContract")
	@ResponseWrapper(localName = "CancelTicketContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.CancelTicketContractResponse")
	public String cancelTicketContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengerName", targetNamespace = "") String passengerName,
			@WebParam(name = "cancel_notify_url", targetNamespace = "") String cancelNotifyUrl,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnr
	 * @param userName
	 * @param linkman
	 * @param appUserName
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrBookDetailContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrBookDetailContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookDetailContract")
	@ResponseWrapper(localName = "PnrBookDetailContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookDetailContractResponse")
	public String pnrBookDetailContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "linkman", targetNamespace = "") String linkman,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outOrderid
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Order_QueryContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Order_QueryContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryContract")
	@ResponseWrapper(localName = "Order_QueryContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryContractResponse")
	public String orderQueryContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outOrderid
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Order_QueryAirid")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Order_QueryAirid", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryAirid")
	@ResponseWrapper(localName = "Order_QueryAiridResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryAiridResponse")
	public String orderQueryAirid(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAllAirp")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAllAirp", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAllAirp")
	@ResponseWrapper(localName = "QueryAllAirpResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAllAirpResponse")
	public String queryAllAirp(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param passengerInfo
	 * @param userName
	 * @param outorderid
	 * @param orderid
	 * @param discFloat
	 * @param encryptString
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AutoBookTicket")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AutoBookTicket", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AutoBookTicket")
	@ResponseWrapper(localName = "AutoBookTicketResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AutoBookTicketResponse")
	public String autoBookTicket(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "encryptString", targetNamespace = "") String encryptString,
			@WebParam(name = "passengerInfo", targetNamespace = "") String passengerInfo,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "outorderid", targetNamespace = "") String outorderid,
			@WebParam(name = "discFloat", targetNamespace = "") String discFloat,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @param appUserName
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrBookContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrBookContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBookContract")
	@ResponseWrapper(localName = "ParsePnrBookContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBookContractResponse")
	public String parsePnrBookContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrMatchAirp")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrMatchAirp", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirp")
	@ResponseWrapper(localName = "ParsePnrMatchAirpResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirpResponse")
	public String parsePnrMatchAirp(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @param linkman
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrBookDetail")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrBookDetail", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBookDetail")
	@ResponseWrapper(localName = "ParsePnrBookDetailResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBookDetailResponse")
	public String parsePnrBookDetail(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "linkman", targetNamespace = "") String linkman,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param changeNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @param changeMemo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ChangeContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ChangeContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ChangeContract")
	@ResponseWrapper(localName = "ChangeContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ChangeContractResponse")
	public String changeContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "changeMemo", targetNamespace = "") String changeMemo,
			@WebParam(name = "change_notify_url", targetNamespace = "") String changeNotifyUrl,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param childibePrice
	 * @param orderIdhis
	 * @param adultplcid
	 * @param adultextReward
	 * @param sign
	 * @param outOrderid
	 * @param adultdisc
	 * @param childdisc
	 * @param userName
	 * @param childplcid
	 * @param childextReward
	 * @param childpnr
	 * @param adultpnr
	 * @param adultibePrice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrBookAdultWithChild")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrBookAdultWithChild", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookAdultWithChild")
	@ResponseWrapper(localName = "PnrBookAdultWithChildResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookAdultWithChildResponse")
	public String pnrBookAdultWithChild(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "adultpnr", targetNamespace = "") String adultpnr,
			@WebParam(name = "childpnr", targetNamespace = "") String childpnr,
			@WebParam(name = "adultplcid", targetNamespace = "") String adultplcid,
			@WebParam(name = "childplcid", targetNamespace = "") String childplcid,
			@WebParam(name = "adultibePrice", targetNamespace = "") String adultibePrice,
			@WebParam(name = "childibePrice", targetNamespace = "") String childibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "adultdisc", targetNamespace = "") String adultdisc,
			@WebParam(name = "childdisc", targetNamespace = "") String childdisc,
			@WebParam(name = "adultextReward", targetNamespace = "") String adultextReward,
			@WebParam(name = "childextReward", targetNamespace = "") String childextReward,
			@WebParam(name = "OrderIdhis", targetNamespace = "") String orderIdhis,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param fileUrl
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirpSyncZip")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirpSyncZip", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpSyncZip")
	@ResponseWrapper(localName = "QueryAirpSyncZipResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpSyncZipResponse")
	public String queryAirpSyncZip(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "fileUrl", targetNamespace = "") String fileUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startTime
	 * @param startDate
	 * @param dstCity
	 * @param userName
	 * @param airCompany
	 * @param orgCity
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryFlightInfo")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryFlightInfo", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryFlightInfo")
	@ResponseWrapper(localName = "QueryFlightInfoResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryFlightInfoResponse")
	public String queryFlightInfo(
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dstCity", targetNamespace = "") String dstCity,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "startTime", targetNamespace = "") String startTime,
			@WebParam(name = "airCompany", targetNamespace = "") String airCompany,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrMatchAirpContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrMatchAirpContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirpContract")
	@ResponseWrapper(localName = "ParsePnrMatchAirpContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirpContractResponse")
	public String parsePnrMatchAirpContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param invNo
	 * @param ticketNo
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PrintInv")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PrintInv", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PrintInv")
	@ResponseWrapper(localName = "PrintInvResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PrintInvResponse")
	public String printInv(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "ticketNo", targetNamespace = "") String ticketNo,
			@WebParam(name = "invNo", targetNamespace = "") String invNo,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param pnr
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrMatchAirp")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrMatchAirp", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrMatchAirp")
	@ResponseWrapper(localName = "PnrMatchAirpResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrMatchAirpResponse")
	public String pnrMatchAirp(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startDate
	 * @param cabin
	 * @param flightNo
	 * @param airSeg
	 * @param dstCity
	 * @param airComp
	 * @param orgCity
	 * @param userName
	 * @param plcid
	 * @param userType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AirpQueryStatusBusiness")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AirpQueryStatusBusiness", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpQueryStatusBusiness")
	@ResponseWrapper(localName = "AirpQueryStatusBusinessResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpQueryStatusBusinessResponse")
	public String airpQueryStatusBusiness(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dstCity", targetNamespace = "") String dstCity,
			@WebParam(name = "airComp", targetNamespace = "") String airComp,
			@WebParam(name = "cabin", targetNamespace = "") String cabin,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "flightNo", targetNamespace = "") String flightNo,
			@WebParam(name = "userType", targetNamespace = "") String userType,
			@WebParam(name = "airSeg", targetNamespace = "") String airSeg,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrMatchAirpNoPat")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrMatchAirpNoPat", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirpNoPat")
	@ResponseWrapper(localName = "ParsePnrMatchAirpNoPatResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirpNoPatResponse")
	public String parsePnrMatchAirpNoPat(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outOrderid
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Order_QueryAiridContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Order_QueryAiridContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryAiridContract")
	@ResponseWrapper(localName = "Order_QueryAiridContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryAiridContractResponse")
	public String orderQueryAiridContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param invNo
	 * @param ticketNo
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "VoidInv")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "VoidInv", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.VoidInv")
	@ResponseWrapper(localName = "VoidInvResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.VoidInvResponse")
	public String voidInv(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "ticketNo", targetNamespace = "") String ticketNo,
			@WebParam(name = "invNo", targetNamespace = "") String invNo,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outNotifyUrl
	 * @param isAutoCancel
	 * @param cancelNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param payPlatform
	 * @param payNotifyUrl
	 * @param totalPrice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AutoOutTickets")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AutoOutTickets", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AutoOutTickets")
	@ResponseWrapper(localName = "AutoOutTicketsResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AutoOutTicketsResponse")
	public String autoOutTickets(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "totalPrice", targetNamespace = "") String totalPrice,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "pay_notify_url", targetNamespace = "") String payNotifyUrl,
			@WebParam(name = "out_notify_url", targetNamespace = "") String outNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign,
			@WebParam(name = "isAutoCancel", targetNamespace = "") String isAutoCancel,
			@WebParam(name = "cancel_notify_url", targetNamespace = "") String cancelNotifyUrl);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param modifyTime
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ModifyAirpSyncTime")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ModifyAirpSyncTime", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ModifyAirpSyncTime")
	@ResponseWrapper(localName = "ModifyAirpSyncTimeResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ModifyAirpSyncTimeResponse")
	public String modifyAirpSyncTime(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "modifyTime", targetNamespace = "") String modifyTime,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param isDifferentPrice
	 * @param ibePrice
	 * @param outUrl
	 * @param childPnr
	 * @param userName
	 * @param adultPnr
	 * @param payUrl
	 * @param payPlatform
	 * @param plcid
	 * @param outOrderId
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrBookAndPayOut")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrBookAndPayOut", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookAndPayOut")
	@ResponseWrapper(localName = "PnrBookAndPayOutResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookAndPayOutResponse")
	public String pnrBookAndPayOut(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "adultPnr", targetNamespace = "") String adultPnr,
			@WebParam(name = "childPnr", targetNamespace = "") String childPnr,
			@WebParam(name = "outOrderId", targetNamespace = "") String outOrderId,
			@WebParam(name = "outUrl", targetNamespace = "") String outUrl,
			@WebParam(name = "payUrl", targetNamespace = "") String payUrl,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "isDifferentPrice", targetNamespace = "") String isDifferentPrice,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param changeNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param changeMemo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Change")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Change", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.Change")
	@ResponseWrapper(localName = "ChangeResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ChangeResponse")
	public String change(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "changeMemo", targetNamespace = "") String changeMemo,
			@WebParam(name = "change_notify_url", targetNamespace = "") String changeNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param cancelNotifyUrl
	 * @param passengerName
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CancelTicket")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "CancelTicket", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.CancelTicket")
	@ResponseWrapper(localName = "CancelTicketResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.CancelTicketResponse")
	public String cancelTicket(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "passengerName", targetNamespace = "") String passengerName,
			@WebParam(name = "cancel_notify_url", targetNamespace = "") String cancelNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outOrderid
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Order_Query")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Order_Query", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQuery")
	@ResponseWrapper(localName = "Order_QueryResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.OrderQueryResponse")
	public String orderQuery(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param appUserName
	 * @param payPlatform
	 * @param payNotifyUrl
	 * @param totalPrice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PayOutContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PayOutContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PayOutContract")
	@ResponseWrapper(localName = "PayOutContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PayOutContractResponse")
	public String payOutContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "totalPrice", targetNamespace = "") String totalPrice,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "pay_notify_url", targetNamespace = "") String payNotifyUrl,
			@WebParam(name = "out_notify_url", targetNamespace = "") String outNotifyUrl,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param startTime
	 * @param sign
	 * @param startDate
	 * @param cabin
	 * @param flight
	 * @param dstCity
	 * @param airComp
	 * @param orgCity
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirp")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirp", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirp")
	@ResponseWrapper(localName = "QueryAirpResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpResponse")
	public String queryAirp(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign,
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dstCity", targetNamespace = "") String dstCity,
			@WebParam(name = "airComp", targetNamespace = "") String airComp,
			@WebParam(name = "flight", targetNamespace = "") String flight,
			@WebParam(name = "cabin", targetNamespace = "") String cabin,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param sign
	 * @param startdate
	 * @param passengername
	 * @param ordaird
	 * @param userName
	 * @param pnr
	 * @param orderid
	 * @param enddate
	 * @param type
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryReserveOrder")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryReserveOrder", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryReserveOrder")
	@ResponseWrapper(localName = "QueryReserveOrderResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryReserveOrderResponse")
	public String queryReserveOrder(
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "ordaird", targetNamespace = "") String ordaird,
			@WebParam(name = "passengername", targetNamespace = "") String passengername,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "type", targetNamespace = "") String type,
			@WebParam(name = "startdate", targetNamespace = "") String startdate,
			@WebParam(name = "enddate", targetNamespace = "") String enddate,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outNotifyUrl
	 * @param isAutoCancel
	 * @param cancelNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param payPlatform
	 * @param payNotifyUrl
	 * @param totalPrice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AutoOut")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AutoOut", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AutoOut")
	@ResponseWrapper(localName = "AutoOutResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AutoOutResponse")
	public String autoOut(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "totalPrice", targetNamespace = "") String totalPrice,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "pay_notify_url", targetNamespace = "") String payNotifyUrl,
			@WebParam(name = "out_notify_url", targetNamespace = "") String outNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign,
			@WebParam(name = "isAutoCancel", targetNamespace = "") String isAutoCancel,
			@WebParam(name = "cancel_notify_url", targetNamespace = "") String cancelNotifyUrl);

	/**
	 * 
	 * @param sign
	 * @param outOrderid
	 * @param userName
	 * @param orderid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryOrderInfo")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryOrderInfo", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryOrderInfo")
	@ResponseWrapper(localName = "QueryOrderInfoResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryOrderInfoResponse")
	public String queryOrderInfo(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param cabin
	 * @param flightNo
	 * @param departureDateTime
	 * @param departureCode
	 * @param userName
	 * @param adultPnr
	 * @param arrivalCode
	 * @param passengerXml
	 * @param officeNum
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CreatePnr")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "CreatePnr", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.CreatePnr")
	@ResponseWrapper(localName = "CreatePnrResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.CreatePnrResponse")
	public String createPnr(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "officeNum", targetNamespace = "") String officeNum,
			@WebParam(name = "passengerXml", targetNamespace = "") String passengerXml,
			@WebParam(name = "adultPnr", targetNamespace = "") String adultPnr,
			@WebParam(name = "flightNo", targetNamespace = "") String flightNo,
			@WebParam(name = "cabin", targetNamespace = "") String cabin,
			@WebParam(name = "departureCode", targetNamespace = "") String departureCode,
			@WebParam(name = "arrivalCode", targetNamespace = "") String arrivalCode,
			@WebParam(name = "departureDateTime", targetNamespace = "") String departureDateTime,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnr
	 * @param userName
	 * @param discFloat
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrAutoBook")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrAutoBook", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrAutoBook")
	@ResponseWrapper(localName = "PnrAutoBookResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrAutoBookResponse")
	public String pnrAutoBook(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "discFloat", targetNamespace = "") String discFloat,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param outNotifyUrl
	 * @param userName
	 * @param orderid
	 * @param payPlatform
	 * @param payNotifyUrl
	 * @param totalPrice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PayOutAdultwithChild")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PayOutAdultwithChild", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PayOutAdultwithChild")
	@ResponseWrapper(localName = "PayOutAdultwithChildResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PayOutAdultwithChildResponse")
	public String payOutAdultwithChild(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "totalPrice", targetNamespace = "") String totalPrice,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "pay_notify_url", targetNamespace = "") String payNotifyUrl,
			@WebParam(name = "out_notify_url", targetNamespace = "") String outNotifyUrl,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param returnCount
	 * @param airXml
	 * @param passengerType
	 * @param plcType
	 * @param userName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirpByXml")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirpByXml", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpByXml")
	@ResponseWrapper(localName = "QueryAirpByXmlResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpByXmlResponse")
	public String queryAirpByXml(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign,
			@WebParam(name = "airXml", targetNamespace = "") String airXml,
			@WebParam(name = "passengerType", targetNamespace = "") String passengerType,
			@WebParam(name = "plcType", targetNamespace = "") String plcType,
			@WebParam(name = "returnCount", targetNamespace = "") String returnCount);

	/**
	 * 
	 * @param sign
	 * @param airpSource
	 * @param tickType
	 * @param userName
	 * @param airpGet
	 * @param encryptString
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirpolicy")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirpolicy", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.QueryAirpolicy")
	@ResponseWrapper(localName = "QueryAirpolicyResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "plfx.yeexing.pojo.bean.QueryAirpolicyResponse")
	public String queryAirpolicy(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "encryptString", targetNamespace = "") String encryptString,
			@WebParam(name = "airpGet", targetNamespace = "") String airpGet,
			@WebParam(name = "airpSource", targetNamespace = "") String airpSource,
			@WebParam(name = "tickType", targetNamespace = "") String tickType,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param userName
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "UserUnsign")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "UserUnsign", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.UserUnsign")
	@ResponseWrapper(localName = "UserUnsignResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.UserUnsignResponse")
	public String userUnsign(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param pnr
	 * @param userName
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrMatchAirpContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrMatchAirpContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrMatchAirpContract")
	@ResponseWrapper(localName = "PnrMatchAirpContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrMatchAirpContractResponse")
	public String pnrMatchAirpContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param id
	 * @param payPrice
	 * @param ordaird
	 * @param userName
	 * @param orderid
	 * @param payPlatform
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Reserve")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Reserve", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.Reserve")
	@ResponseWrapper(localName = "ReserveResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ReserveResponse")
	public String reserve(
			@WebParam(name = "id", targetNamespace = "") String id,
			@WebParam(name = "orderid", targetNamespace = "") String orderid,
			@WebParam(name = "ordaird", targetNamespace = "") String ordaird,
			@WebParam(name = "payPrice", targetNamespace = "") String payPrice,
			@WebParam(name = "payPlatform", targetNamespace = "") String payPlatform,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airId
	 * @param userName
	 * @param type
	 * @param orderId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "TicketSuspendAndResume")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "TicketSuspendAndResume", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.TicketSuspendAndResume")
	@ResponseWrapper(localName = "TicketSuspendAndResumeResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.TicketSuspendAndResumeResponse")
	public String ticketSuspendAndResume(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "orderId", targetNamespace = "") String orderId,
			@WebParam(name = "airId", targetNamespace = "") String airId,
			@WebParam(name = "type", targetNamespace = "") String type,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param adultIbePrice
	 * @param childIbePrice
	 * @param adultPlcId
	 * @param childPlcId
	 * @param childPnr
	 * @param userName
	 * @param adultPnr
	 * @param appUserName
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrBookWithChild")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "PnrBookWithChild", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookWithChild")
	@ResponseWrapper(localName = "PnrBookWithChildResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.PnrBookWithChildResponse")
	public String pnrBookWithChild(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "adultPnr", targetNamespace = "") String adultPnr,
			@WebParam(name = "childPnr", targetNamespace = "") String childPnr,
			@WebParam(name = "adultPlcId", targetNamespace = "") String adultPlcId,
			@WebParam(name = "childPlcId", targetNamespace = "") String childPlcId,
			@WebParam(name = "adultIbePrice", targetNamespace = "") String adultIbePrice,
			@WebParam(name = "childIbePrice", targetNamespace = "") String childIbePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param extReward
	 * @param outOrderid
	 * @param ibePrice
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @param plcid
	 * @param disc
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrBook")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrBook", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBook")
	@ResponseWrapper(localName = "ParsePnrBookResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrBookResponse")
	public String parsePnrBook(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "ibePrice", targetNamespace = "") String ibePrice,
			@WebParam(name = "out_orderid", targetNamespace = "") String outOrderid,
			@WebParam(name = "disc", targetNamespace = "") String disc,
			@WebParam(name = "extReward", targetNamespace = "") String extReward,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param airpSource
	 * @param tickType
	 * @param userName
	 * @param airpGet
	 * @param encryptString
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryAirpolicyByGoldTime")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryAirpolicyByGoldTime", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpolicyByGoldTime")
	@ResponseWrapper(localName = "QueryAirpolicyByGoldTimeResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryAirpolicyByGoldTimeResponse")
	public String queryAirpolicyByGoldTime(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "encryptString", targetNamespace = "") String encryptString,
			@WebParam(name = "airpGet", targetNamespace = "") String airpGet,
			@WebParam(name = "airpSource", targetNamespace = "") String airpSource,
			@WebParam(name = "tickType", targetNamespace = "") String tickType,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startTime
	 * @param userName
	 * @param type
	 * @param endTime
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryBuyTicketsList")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryBuyTicketsList", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryBuyTicketsList")
	@ResponseWrapper(localName = "QueryBuyTicketsListResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryBuyTicketsListResponse")
	public String queryBuyTicketsList(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "startTime", targetNamespace = "") String startTime,
			@WebParam(name = "endTime", targetNamespace = "") String endTime,
			@WebParam(name = "type", targetNamespace = "") String type,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startDate
	 * @param cabin
	 * @param flightNo
	 * @param airSeg
	 * @param dstCity
	 * @param airComp
	 * @param orgCity
	 * @param userName
	 * @param appUserName
	 * @param plcid
	 * @param userType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AirpQueryStatusBusinessContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AirpQueryStatusBusinessContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpQueryStatusBusinessContract")
	@ResponseWrapper(localName = "AirpQueryStatusBusinessContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.AirpQueryStatusBusinessContractResponse")
	public String airpQueryStatusBusinessContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "plcid", targetNamespace = "") String plcid,
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dstCity", targetNamespace = "") String dstCity,
			@WebParam(name = "airComp", targetNamespace = "") String airComp,
			@WebParam(name = "cabin", targetNamespace = "") String cabin,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "flightNo", targetNamespace = "") String flightNo,
			@WebParam(name = "userType", targetNamespace = "") String userType,
			@WebParam(name = "airSeg", targetNamespace = "") String airSeg,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param pnrText
	 * @param pnr
	 * @param userName
	 * @param appUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnrMatchAirpNoPatContract")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ParsePnrMatchAirpNoPatContract", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirpNoPatContract")
	@ResponseWrapper(localName = "ParsePnrMatchAirpNoPatContractResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.ParsePnrMatchAirpNoPatContractResponse")
	public String parsePnrMatchAirpNoPatContract(
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "appUserName", targetNamespace = "") String appUserName,
			@WebParam(name = "pnr", targetNamespace = "") String pnr,
			@WebParam(name = "pnrText", targetNamespace = "") String pnrText,
			@WebParam(name = "sign", targetNamespace = "") String sign);

	/**
	 * 
	 * @param sign
	 * @param startTime
	 * @param startDate
	 * @param dstCity
	 * @param userName
	 * @param airCompany
	 * @param orgCity
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QueryFlightPrice")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "QueryFlightPrice", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryFlightPrice")
	@ResponseWrapper(localName = "QueryFlightPriceResponse", targetNamespace = "http://service.webservice.yeexing.com", className = "com.yeexing.webservice.service.QueryFlightPriceResponse")
	public String queryFlightPrice(
			@WebParam(name = "orgCity", targetNamespace = "") String orgCity,
			@WebParam(name = "dstCity", targetNamespace = "") String dstCity,
			@WebParam(name = "startDate", targetNamespace = "") String startDate,
			@WebParam(name = "startTime", targetNamespace = "") String startTime,
			@WebParam(name = "airCompany", targetNamespace = "") String airCompany,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "sign", targetNamespace = "") String sign);

}
