package plfx.yeexing.util;

import hg.common.util.SysProperties;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import plfx.yeexing.inter.IBEServicePortType;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * IBEService service = new IBEService();
 * IBEServicePortType portType = service.getIBEServiceHttpPort();
 * portType.queryAirpolicyNoEncrypt(...);
 * </pre>
 * 
 * </p>
 * 
 */
//@WebServiceClient(name = "IBEService", targetNamespace = "http://service.webservice.yeexing.com", wsdlLocation = "http://jk.yeexing.net/CXF/services/IBEService?wsdl")
//@WebServiceClient(name = "IBEService", targetNamespace = "http://service.webservice.yeexing.com", wsdlLocation = "http://service1.yeexing.com.cn/CXF/services/IBEService?wsdl")
public class IBEService extends Service {

	private final static URL IBESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(IBEService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = IBEService.class
					.getResource(".");
//			url = new URL(baseUrl,
//					"http://jk.yeexing.net/CXF/services/IBEService?wsdl");
//			url = new URL(baseUrl,
//					"http://service1.yeexing.com.cn/CXF/services/IBEService?wsdl");
//			url = new URL(baseUrl,"http://service1.yeexing.com.cn/CXF/services/IBEService?wsdl");
			//从cc读取配置
			url = new URL(baseUrl,SysProperties.getInstance().get("yxgn_url"));
			logger.info("从配置文件中加载易行国内机票接口地址...");
		} catch (MalformedURLException e) {
//			logger.warning("Failed to create URL for the wsdl Location: 'http://jk.yeexing.net/CXF/services/IBEService?wsdl', retrying as a local file");
//			logger.warning("Failed to create URL for the wsdl Location: 'http://service1.yeexing.com.cn/CXF/services/IBEService?wsdl");
//			logger.warning(e.getMessage());
		}
		IBESERVICE_WSDL_LOCATION = url;
	}

	public IBEService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IBEService() {
		super(IBESERVICE_WSDL_LOCATION, new QName(
				"http://service.webservice.yeexing.com", "IBEService"));
	}

	/**
	 * 
	 * @return returns IBEServicePortType
	 */
	@WebEndpoint(name = "IBEServiceHttpPort")
	public IBEServicePortType getIBEServiceHttpPort() {
		return super.getPort(new QName("http://service.webservice.yeexing.com",
				"IBEServiceHttpPort"), IBEServicePortType.class);
	}

}
