//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 10:29:41 AM CST 
//


package plfx.jd.pojo.system.enumConstants;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumSortType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnumSortType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Default"/>
 *     &lt;enumeration value="StarRankDesc"/>
 *     &lt;enumeration value="RateAsc"/>
 *     &lt;enumeration value="DistanceAsc"/>
 *     &lt;enumeration value="RateDesc"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EnumSortType")
@XmlEnum
public enum EnumSortType {

	/***
	 * Default艺龙默认排序

       StarRankDesc推荐星级降序

       RateAsc价格升序

       RateDesc价格降序

       DistanceAsc距离升序

	 */
    @XmlEnumValue("Default")
    Default("Default"),
    @XmlEnumValue("StarRankDesc")
    StarRankDesc("StarRankDesc"),
    @XmlEnumValue("RateAsc")
    RateAsc("RateAsc"),
    @XmlEnumValue("DistanceAsc")
    DistanceAsc("DistanceAsc"),
    @XmlEnumValue("RateDesc")
    RateDesc("RateDesc");
    private final String value;

    EnumSortType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnumSortType fromValue(String v) {
        for (EnumSortType c: EnumSortType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
